import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TailwindIndicator } from "@/components/ui/tailwind-indicator";
import { cn } from "@/lib/utils";
import { inter } from "@/lib/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'w-screen overflow-x-hidden scroll-smooth')}>
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}
