import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TailwindIndicator } from "@/components/ui/tailwind-indicator";
import {cn } from '@/lib/utils'
const inter = Inter({ subsets: ["latin"] });
import polySans from '@/utils/fonts'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ cn(inter.className,polySans.variable )}>{children}
      <TailwindIndicator />
      </body>
    </html>
  );
}
